use gpui::actions;

// LEARN: GPUI actions are zero-sized types generated by this macro.
// Each action is a unique Rust type (e.g. `struct SpawnTerminal;`) that can be
// dispatched through the UI tree. This gives compile-time guarantees that event
// handlers match the right events — no stringly-typed event names like in JS frameworks.
// Keybindings are registered as (key_combo -> ActionType) pairs.
actions!(arbor, [
    ShowAbout,
    RequestQuit,
    ImmediateQuit,
    NewWindow,
    SpawnTerminal,
    CloseActiveTerminal,
    OpenManagePresets,
    OpenManageRepoPresets,
    RefreshWorktrees,
    RefreshChanges,
    OpenAddRepository,
    OpenCreateWorktree,
    ToggleLeftPane,
    NavigateWorktreeBack,
    NavigateWorktreeForward,
    CollapseAllRepositories,
    ViewLogs,
    OpenCommandPalette,
    OpenThemePicker,
    OpenSettings,
    OpenManageHosts,
    ConnectToHost,
    RefreshReviewComments
]);

#[derive(Clone, PartialEq, Debug, gpui::Action)]
#[action(namespace = arbor, no_json)]
pub struct ConnectToLanDaemon {
    pub index: usize,
}
